# Generated by Django 4.2.9 on 2024-08-15 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubcriptionRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=200)),
                ('prompt', models.CharField(max_length=200)),
                ('location', models.JSONField(null=True)),
                ('provider_code', models.CharField(default='DG', max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
