# Generated by Django 4.2.9 on 2024-08-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriptionrequest',
            name='prompt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
