# Generated by Django 4.2.9 on 2024-08-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docgen_api', '0002_alter_subcriptionrequest_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcriptionrequest',
            name='status',
        ),
    ]
