# Generated by Django 4.2.9 on 2024-08-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen_api', '0003_remove_subcriptionrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriptionrequest',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
