# Generated by Django 4.2.9 on 2024-08-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docgen_api', '0006_subcriptionrequestfile_gen_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcriptionrequestfile',
            name='gen_file_path',
        ),
    ]
