version: '3.8'

networks:
    imgen-network:
      driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BE_HOST: ${BE_HOST}
        - BE_PORT: ${BE_PORT}
    restart: always
    # command: python run.py
    env_file:
      - .env
    networks:
      - imgen-network
    ports:
      - "${BE_PORT}:${BE_PORT}"
    depends_on:
      - ai-worker
      - redis
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  ai-worker:
    build:
      context: ./ai_worker
      dockerfile: Dockerfile
      args:
        - AI_WORKER_HOST: ${AI_WORKER_HOST}
        - AI_WORKER_PORT: ${AI_WORKER_PORT}
    restart: always
    # command: python worker.py
    env_file:
      - .env
    networks:
      - imgen-network
    ports:
      - "${AI_WORKER_PORT}:${AI_WORKER_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    # command: nginx -g daemon off;
    env_file:
      - .env
    networks:
      - imgen-network
    ports:
      - "3000:80"

  redis:
    image: redis:6.2-alpine
    networks:
      - imgen-network
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  minio:
    image: minio/minio
    env_file:
      - .env
    networks:
      - imgen-network
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_SECOND_PORT}:${MINIO_SECOND_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    # command: server /data
    volumes:
      - "./data/volume/minio:/data"
    command: server /data --address ":${MINIO_PORT}" --console-address ":${MINIO_SECOND_PORT}"

  celery_worker:
    build: ./backend
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - backend
      - redis
      - minio
    env_file:
      - .env
    networks:
      - imgen-network
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
